// This file was generated by [`export_ts` from the Holochain project](https://github.com/holochain/holochain/tree/main/crates/export_ts). Do not edit this file manually.

/** Raw hash types */

export type HoloHash = Uint8Array; // length 39
export type AgentPubKey = HoloHash;
export type DnaHash = HoloHash;
export type WasmHash = HoloHash;
export type EntryHash = HoloHash;
export type ActionHash = HoloHash;
export type AnyDhtHash = HoloHash;
export type AnyLinkableHash = HoloHash;
export type ExternalHash = HoloHash;

/** Base64 hash types */

export type HoloHashB64 = string;
export type AgentPubKeyB64 = HoloHashB64;
export type DnaHashB64 = HoloHashB64;
export type WasmHashB64 = HoloHashB64;
export type EntryHashB64 = HoloHashB64;
export type ActionHashB64 = HoloHashB64;
export type AnyDhtHashB64 = HoloHashB64;
export type AnyLinkableHashB64 = HoloHashB64;
export type ExternalHashB64 = HoloHashB64;
