use crate::integrity::*;
use hdk::prelude::*;

/// The payload encoded as `init_properties` when installing the migration target.
///
/// Assembled by the migrating agent on the old DNA.
#[derive(Debug, serde::Serialize, serde::Deserialize, SerializedBytes)]
struct InitPropertiesPayload {
    /// Serialised values from all [`MyType`] entries on the old DNA's chain. Generated by the
    /// `prepare_migration_summary` function.
    pub summary: Vec<String>,
    /// Signature over `summary` using the agent's own key. Generated by the
    /// `prepare_migration_summary` function on the old DNA.
    pub signature: Signature,
    /// The agent's own public key used to sign the summary to create the signature.
    pub signer: AgentPubKey,
    /// The hash from closing the old chain with `close_chain_for_new()`.
    pub close_hash: ActionHash,
}

#[hdk_extern]
fn init() -> ExternResult<InitCallbackResult> {
    let properties: Properties = dna_info()?.modifiers.properties.try_into().map_err(|_| {
        wasm_error!(WasmErrorInner::Guest(
            "Could not deserialize DNA properties".to_string()
        ))
    })?;

    let Some(init_props) = get_init_properties()? else {
        return Ok(InitCallbackResult::Fail(
            "init_properties are required for chain-switch migration but were not supplied".into(),
        ));
    };

    let payload: InitPropertiesPayload = init_props
        .0
        .try_into()
        .map_err(|e: SerializedBytesError| wasm_error!(e))?;

    // Open the new chain with the real CloseChain hash from the old chain.
    open_chain(properties.prev_dna_hash.into(), payload.close_hash)?;

    // Commit the signed migration record. The integrity zome validates that
    // the signer is trusted and the signature over the summary is correct.
    create_entry(EntryTypes::MigrationRecord(MigrationRecord {
        summary: payload.summary.clone(),
        signature: payload.signature,
        signer: payload.signer,
    }))?;

    // Seed MyType entries derived from the old chain's summary.
    for value in payload.summary {
        create_entry(EntryTypes::MyType(MyType { value, amount: 0 }))?;
    }

    Ok(InitCallbackResult::Pass)
}

#[hdk_extern]
fn create(_: ()) -> ExternResult<ActionHash> {
    create_entry(EntryTypes::MyType(MyType {
        value: "test new".to_string(),
        amount: 4,
    }))
}

#[hdk_extern]
fn get_all_my_types() -> ExternResult<Vec<MyType>> {
    let records = query(
        ChainQueryFilter::new()
            .entry_type(EntryTypesUnit::MyType.try_into().unwrap())
            .include_entries(true),
    )?;

    let my_types = records
        .into_iter()
        .filter_map(|r| {
            let entry = r.entry.into_option()?;
            MyType::try_from(entry).ok()
        })
        .collect();

    Ok(my_types)
}

/// Return the `close_hash` recorded in the [`OpenChain`] action, if one exists.
///
/// Used by integration tests to verify that the real [`CloseChain`] hash from the old chain was
/// carried through `init_properties`.
#[hdk_extern]
fn get_open_chain_close_hash(_: ()) -> ExternResult<Option<ActionHash>> {
    let records = query(ChainQueryFilter::new().action_type(ActionType::OpenChain))?;
    Ok(records.into_iter().find_map(|r| match &r.action().data {
        ActionData::OpenChain(oc) => Some(oc.close_hash.clone()),
        _ => None,
    }))
}
