use hdi::prelude::*;

/// DNA properties for the migration target DNA.
#[derive(Debug, serde::Serialize, serde::Deserialize, SerializedBytes)]
pub struct Properties {
    /// The DNA hash of the chain this DNA migrated from.
    pub prev_dna_hash: holo_hash::DnaHash,
    /// Agent keys whose migration summaries this integrity zome accepts.
    /// Baked into the DNA hash so every peer agrees.
    pub trusted_signers: Vec<AgentPubKey>,
}

/// A type carried from the old DNA, kept for decoding the migration summary.
#[hdk_entry_helper]
pub struct MyOldType {
    pub value: String,
}

#[hdk_entry_helper]
pub struct MyType {
    pub value: String,
    pub amount: u32, // A difference from the original
}

/// Committed during `init` to record the signed migration summary on the chain.
///
/// The integrity zome's `validate` callback checks that `signer` appears in the DNA's
/// `trusted_signers` list and that `signature` is a valid signature over `summary` by `signer`.
#[hdk_entry_helper]
#[derive(Clone)]
pub struct MigrationRecord {
    /// Serialised values from all [`MyType`] entries on the old DNA's chain.
    /// Generated by the `prepare_migration_summary` function.
    pub summary: Vec<String>,
    /// Signature over `summary` using the agent's own key.
    /// Generated by the `prepare_migration_summary` function on the old DNA.
    pub signature: Signature,
    /// The agent's own public key used to sign the summary to create the signature.
    pub signer: AgentPubKey,
}

#[hdk_entry_types]
#[unit_enum(EntryTypesUnit)]
pub enum EntryTypes {
    MyType(MyType),
    MigrationRecord(MigrationRecord),
}

#[hdk_extern]
pub fn validate(op: Op) -> ExternResult<ValidateCallbackResult> {
    match op.flattened::<EntryTypes, ()>()? {
        FlatOp::CreateEntry(OpEntry::CreateEntry {
            app_entry: EntryTypes::MigrationRecord(record),
            ..
        })
        | FlatOp::CreateRecord(OpRecord::CreateEntry {
            app_entry: EntryTypes::MigrationRecord(record),
            ..
        }) => validate_migration_record(record),
        FlatOp::CreateEntry(OpEntry::UpdateEntry {
            app_entry: EntryTypes::MigrationRecord(_),
            ..
        })
        | FlatOp::CreateRecord(OpRecord::UpdateEntry {
            app_entry: EntryTypes::MigrationRecord(_),
            ..
        }) => Ok(ValidateCallbackResult::Invalid(
            "MigrationRecord entries cannot be updated".into(),
        )),
        _ => Ok(ValidateCallbackResult::Valid),
    }
}

fn validate_migration_record(record: MigrationRecord) -> ExternResult<ValidateCallbackResult> {
    let properties: Properties = dna_info()?.modifiers.properties.try_into().map_err(|_| {
        wasm_error!(WasmErrorInner::Guest(
            "Could not deserialize DNA properties".to_string()
        ))
    })?;

    if !properties.trusted_signers.contains(&record.signer) {
        return Ok(ValidateCallbackResult::Invalid(
            "Migration summary signer is not listed in trusted_signers".into(),
        ));
    }

    if !verify_signature(record.signer, record.signature, record.summary)? {
        return Ok(ValidateCallbackResult::Invalid(
            "Migration summary signature is invalid".into(),
        ));
    }

    Ok(ValidateCallbackResult::Valid)
}
