FROM holochain/holonix:latest

WORKDIR /holochain/build
ENV NIX_ENV_PREFIX /holochain/build

ARG DOCKER_BRANCH=develop
ARG GITHUB_ACCESS_TOKEN=xxxx

ADD https://api.github.com/repos/holochain/holochain/tarball/$DOCKER_BRANCH?access_token=$GITHUB_ACCESS_TOKEN /holochain/build/$DOCKER_BRANCH.tar.gz
RUN tar --strip-components=1 -zxvf $DOCKER_BRANCH.tar.gz

# warm things
RUN nix-shell --run echo
