FROM holochain/holonix:latest

WORKDIR /holochain/build
ENV NIX_ENV_PREFIX /holochain/build

ARG DOCKER_BRANCH=develop

ADD https://github.com/holochain/holochain/archive/$DOCKER_BRANCH.tar.gz /holochain/build/$DOCKER_BRANCH.tar.gz
RUN tar --strip-components=1 -zxvf $DOCKER_BRANCH.tar.gz

# warm things
RUN nix-shell --run echo
