[package]
name = "test_wasm_paths"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2021"
publish = false

[lib]
name = "test_wasm_paths"
crate-type = ["cdylib", "rlib"]

[[example]]
name = "integrity_test_wasm_paths"
path = "src/integrity.rs"
crate-type = ["cdylib", "rlib"]

# reminder - do not use workspace deps
[dependencies]
hdk = { version = "0.9.0-dev.0" }
hdi = { version = "=0.9.0-dev.4" }
holochain_serialized_bytes = "*"
serde = "1.0"

[features]
default = []
mock = ["hdk/mock"]
