[package]
name = "holochain_state_types"
version = "0.8.0-dev.0"
description = "Types for the holochain_state crate"
license = "Apache-2.0"
repository = "https://github.com/holochain/holochain"
documentation = "https://docs.rs/holochain_state_types"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2021"

# reminder - do not use workspace deps
[dependencies]
holo_hash = { version = "^0.8.0-dev.0", path = "../holo_hash" }
holochain_integrity_types = { version = "^0.8.0-dev.0", path = "../holochain_integrity_types", default-features = false }
serde = { version = "1.0", features = ["derive"] }
ts-rs = { version = "12.0", features = ["no-serde-warnings"], optional = true }

[lints]
workspace = true

[features]
ts_rs = ["dep:ts-rs", "holo_hash/ts_rs", "holochain_integrity_types/ts_rs"]
