{
 "title": "Holochain",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Run count (task loops)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(run_count_total[5m])" }
   ]
  },
  {
   "title": "Admin connection count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(listen_port) (conn_count{designation=\"admin\"})"
    }
   ]
  },
  {
   "title": "App connection count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(listen_port) (conn_count{designation=\"app\"})"
    }
   ]
  },
  {
   "title": "Admin websocket request/response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(request_response_duration_sum{handler_name=\"ws_admin_request_response_duration\"}[5m])) * 1000) / sum(rate(request_response_duration_count{handler_name=\"ws_admin_request_response_duration\"}[5m]))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "App websocket request/response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(request_response_duration_sum{handler_name=\"ws_app_request_response_duration\"}[5m])) * 1000) / sum(rate(request_response_duration_count{handler_name=\"ws_app_request_response_duration\"}[5m]))",
     "legendFormat": "duration"
    }
   ]
  }
 ]
}