//! Signals which can be emitted from within Holochain, out across an interface.
//! There are two main kinds of Signal: system-defined, and app-defined:
//! - App-defined signals are produced via the `emit_signal!` host function.
//! - System-defined signals are produced in various places in the system

use crate::cell::CellId;
use holochain_serialized_bytes::SerializedBytes;

/// A Signal is some information emitted from within Holochain out through
/// an Interface
pub enum Signal {
    /// Signal from a Cell, generated by `emit_signal!`
    App(CellId, SerializedBytes),
    /// System-defined signals
    System(SystemSignal),
}

/// A Signal which originates from within the Holochain system, as opposed to
/// from within a Cell
pub enum SystemSignal {
    // e.g.:
// DataAvailable(AnyDhtHash),
}
