DROP TABLE IF EXISTS BlockSpan;
DROP TABLE IF EXISTS Nonce;
DROP TABLE IF EXISTS SignalSubscription;
DROP TABLE IF EXISTS AppInterface;
DROP TABLE IF EXISTS CloneCell;
DROP TABLE IF EXISTS AppRole;
DROP TABLE IF EXISTS InstalledApp;
DROP TABLE IF EXISTS Conductor;
